# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0004_auto_20180424_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='appointment',
        ),
    ]
